### ISSUE TITLE
Logs at debug level don't get classified as debug in firefox

### ISSUE THREAD

**Issue by MinmoTech** [LighthouseGames/KmLogging#15]
![image](https://github.com/LighthouseGames/KmLogging/assets/25890405/6e472a51-c7e1-4ced-b0be-411479e72eb2)

On Firefox, logs on the debug level only get hidden when you hide the "logs" category instead of the "debug" category.

I assume the cause is that the "debug" category seems to not exist on chromium

**Comment by ellsworthrw** [comment]
Kotlin does not yet have a method to expose log levels more verbose than Info.
