### ISSUE TITLE
Is the logger thread-safe?

### ISSUE THREAD

**Issue by MinmoTech** [LighthouseGames/KmLogging#16]
I'm wondering if with the usage in the readme access to the logger would be thread-safe?

```kotlin
class MyClass {
    fun easyPeasy() {
        log.i { "use traditional Android short function name" }
    }

    fun easyPeasyLemonSqueesy() {
        log.info { "use longer more explicit function name" }
    }

    companion object {
        val log = logging()
    }
}
```

In this case, if there were 2 instances of `MyClass` and both access `log` at the same time could there be a race condition?

Either way would be fine, it would just be nice if this would be made clear from the readme :slightly_smiling_face:

**Comment by ellsworthrw** [comment]
Yes, the logger is thread safe
